### ISSUE TITLE
Class instance not required

### ISSUE THREAD

**Issue by Putr** [geertw/php-ip-anonymizer#1]
Hi!

This class was exactly what I needed (why reinvent the wheel :D).

But I don't think the object instance is required. You could make the methods static and we can just call them directly.

**Comment by geertw** [comment]
Hi! Nice to hear it's useful :-)

The reason why the object instance is required, is because you can choose a custom network mask. But for convenience, I can add a static method which just uses the default mask.

**Comment by Putr** [comment]
Fair point! Thanks for the extra method, the default is good enough for me :).
